Repository wecode-bootcamp-korea/fullstack3-1st-wepleshop-backend, pull requests merged in 2021-12, with the labels that each got.

#14 Detail API 구현
  controllers/index.js
  controllers/product_detail_controller.js
  models/index.js
  models/product_deatil_dao.js
  routes/index.js
  routes/product_router.js
  services/index.js
  services/product_detail_service.js
Labels: Status: 피어 리뷰 요청

#18 Sorting API
  .eslintrc.json
  controllers/index.js
  controllers/product_sort_controller.js
  models/index.js
  models/product_detail_dao.js
  models/product_sort_dao.js
  prisma/migrations/20211230161039_fifth_init/migration.sql
  prisma/migrations/20211230161623_sixth_init/migration.sql
  prisma/migrations/20211230161742_seventh_init/migration.sql
  prisma/schema.prisma
  routes/index.js
  routes/product_router.js
  services/index.js
  services/product_sort_service.js
Labels: Status: 피어 리뷰 요청

#15 Category API
  .eslintrc.json
  controllers/index.js
  controllers/product_category_controller.js
  controllers/product_sort_controller.js
  models/index.js
  models/product_category_dao.js
  routes/index.js
  routes/product_router.js
  services/index.js
  services/product_category_service.js
Labels: Status: 추가 기능 구현 중, Status: 피어 리뷰 요청

#16 Feature/login signup
  controllers/index.js
  controllers/user_controller.js
  models/index.js
  models/user_dao.js
  package.json
  routes/index.js
  routes/user_router.js
  services/index.js
  services/user_service.js
Labels: Status: Accepted
